// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2uU49dzNfN9lzrubNi4g8LQcZHXp777A',
    appId: '1:826925038249:web:93d2452e9367949b1d47b8',
    messagingSenderId: '826925038249',
    projectId: 'splitsmart-24c51',
    authDomain: 'splitsmart-24c51.firebaseapp.com',
    storageBucket: 'splitsmart-24c51.firebasestorage.app',
    measurementId: 'G-50EH7PHWEY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjQwR0NNkZ4BkdtQpCfLt9OaLsALn-H3A',
    appId: '1:826925038249:ios:fa2adffcb8783b821d47b8',
    messagingSenderId: '826925038249',
    projectId: 'splitsmart-24c51',
    storageBucket: 'splitsmart-24c51.firebasestorage.app',
    iosBundleId: 'com.splitsmart.splitsmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2uU49dzNfN9lzrubNi4g8LQcZHXp777A',
    appId: '1:826925038249:web:4ff0725431df53971d47b8',
    messagingSenderId: '826925038249',
    projectId: 'splitsmart-24c51',
    authDomain: 'splitsmart-24c51.firebaseapp.com',
    storageBucket: 'splitsmart-24c51.firebasestorage.app',
    measurementId: 'G-1R778QKXQK',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjQwR0NNkZ4BkdtQpCfLt9OaLsALn-H3A',
    appId: '1:826925038249:ios:fa2adffcb8783b821d47b8',
    messagingSenderId: '826925038249',
    projectId: 'splitsmart-24c51',
    storageBucket: 'splitsmart-24c51.firebasestorage.app',
    iosBundleId: 'com.splitsmart.splitsmart',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwT9gp365EaWHmjAQZPznpAL6wm4MGRAA',
    appId: '1:826925038249:android:50da94e59b4348dc1d47b8',
    messagingSenderId: '826925038249',
    projectId: 'splitsmart-24c51',
    storageBucket: 'splitsmart-24c51.firebasestorage.app',
  );

}